version: "3.8"
services:
  db:
    image: mongo:latest
    # mapping for Internet to access db
    ports:
      - "2500:27017"
    volumes:
      - /home/rocky/shuttleday-volume:/data/db
    restart: always

  app:
    build: .
    depends_on:
      - db
    ports:
      - "2600:2600"
    # access within subnet
    environment:
      - MONGO_URL=mongodb://db:27017/shuttleday-prod
      - SERVER_PORT=2600
      - AWS_S3_SECRET_ACCESS_KEY=${AWS_S3_SECRET_ACCESS_KEY}
      - AWS_S3_ACCESS_KEY_ID=${AWS_S3_ACCESS_KEY_ID}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
      - G_AUTH_CLIENT_ID=${G_AUTH_CLIENT_ID}
    links:
      - db
    restart: always
