name: Frontend CI

on:
  workflow_dispatch:
  push:
    paths:
      - "bdlist-frontend/"
    branches:
      - main
  pull_request:
    paths:
      - "bdlist-frontend/"
    branches:
      - main
    
defaults:
  run:
    working-directory: ./bdlist-frontend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    
    - name: Install dependencies
      run: npm install

    - name: Build Frontend
      run: npm run build
      env:
        REACT_APP_CLIENT_ID: ${{ secrets.REACT_APP_CLIENT_ID }}
        REACT_APP_API_LINK: ${{ secrets.REACT_APP_API_LINK }}

    - name: Upload React artifacts
      uses: actions/upload-artifact@v3
      with:
        name: static-react-build
        path: ./bdlist-frontend/build/
        retention-days: 14

  deploy:
    # Only run deploy stage if it's a push event
    # if: github.event_name == 'push'
    permissions:
      id-token: write
      contents: read
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download React artifacts
      uses: actions/download-artifact@v3
      with:
        name: static-react-build

    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::714188290514:role/GitHub-Actions-Push-S3
        aws-region: ap-southeast-1

    - name: Push build artifacts to S3 bucket
      run: aws s3 sync build s3://shuttleday.info --recursive
    